
[tool.poetry]
name = "flask_tic_tac_toe"
version = "0.1.0"
description = "Tic-Tac-Toe game using Flask."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
